name: Convert YAML to Ignition JSON

on:
  push:
    branches: [ "master" ]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Butane
        run: |
          wget https://github.com/coreos/butane/releases/download/v0.22.0/butane-x86_64-unknown-linux-gnu
          chmod +x butane-x86_64-unknown-linux-gnu
          sudo mv butane-x86_64-unknown-linux-gnu /usr/local/bin/butane

